@baseUrl=http://localhost:3000

###
GET {{baseUrl}} HTTP/1.1

###
GET {{baseUrl}}/books HTTP/1.1

###
GET {{baseUrl}}/books/1 HTTP/1.1

###
POST {{baseUrl}}/books HTTP/1.1
Content-Type: application/json

{
    "title": "Example book {{$randomInt 1 999}}"
}

###
PUT {{baseUrl}}/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "Example book {{$randomInt 1 999}}"
}